// Generated by https://quicktype.io

// export interface HeroesResponse {
//   heroes: Hero[];
// }

export interface Hero {
  id?:      string;
  name:    string;
  ability: string;
  isAlive: boolean;
}
